[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXTAUTH_URL,ADMIN_MOBILE,ADMIN_NAME,ADMIN_EMAIL,ADMIN_NOTIFICATION_EMAIL,SMS_PROVIDER_SENDER_ID,AUTH_SECRET,CLOUDINARY_CLOUD_NAME,EMAIL_FROM"

[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXTAUTH_URL,ADMIN_MOBILE,ADMIN_NAME,ADMIN_EMAIL,ADMIN_NOTIFICATION_EMAIL,SMS_PROVIDER_SENDER_ID,AUTH_SECRET,CLOUDINARY_CLOUD_NAME,EMAIL_FROM"

[context.deploy-preview.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXTAUTH_URL,ADMIN_MOBILE,ADMIN_NAME,ADMIN_EMAIL,ADMIN_NOTIFICATION_EMAIL,SMS_PROVIDER_SENDER_ID,AUTH_SECRET,CLOUDINARY_CLOUD_NAME,EMAIL_FROM"

[context.branch-deploy.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXTAUTH_URL,ADMIN_MOBILE,ADMIN_NAME,ADMIN_EMAIL,ADMIN_NOTIFICATION_EMAIL,SMS_PROVIDER_SENDER_ID,AUTH_SECRET,CLOUDINARY_CLOUD_NAME,EMAIL_FROM"
